create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  thread_id text not null,
  author_name text not null,
  body text not null,
  is_approved boolean not null default false,
  created_at timestamptz not null default now(),
  constraint comments_author_name_length check (char_length(author_name) between 1 and 80),
  constraint comments_body_length check (char_length(body) between 1 and 5000),
  constraint comments_thread_id_length check (char_length(thread_id) between 1 and 300)
);

create index if not exists comments_thread_created_idx
  on public.comments (thread_id, created_at);

alter table public.comments enable row level security;

-- Public can read approved comments.
drop policy if exists "public read approved comments" on public.comments;
create policy "public read approved comments"
  on public.comments
  for select
  to anon, authenticated
  using (is_approved = true);

-- Public can submit comments, but cannot self-approve.
drop policy if exists "public insert comments (unapproved)" on public.comments;
create policy "public insert comments (unapproved)"
  on public.comments
  for insert
  to anon, authenticated
  with check (
    is_approved = false
    and char_length(author_name) between 1 and 80
    and char_length(body) between 1 and 5000
    and char_length(thread_id) between 1 and 300
  );

